# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb_cookbot', '0002_recipe_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='url',
        ),
    ]
