# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_cookbot', '0003_remove_recipe_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
