# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_cookbot', '0004_recipe_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
